export const RadiologyAppointmentFlattenRow = (appointment) => ({
  id: appointment.id,
  user_id: appointment.user_id,
  fullName:
    `${appointment.user?.first_name || ""} ${appointment.user?.last_name || ""}`.trim(),
  contact: appointment.user?.contact || "",
  email: appointment.user?.email || "",
  labName: appointment.lab?.lab_name || "",
  testDetails: appointment.test_name || [],
  slotTime: appointment.slot_time,
  additional_discount: "₹" + appointment.additional_discount,
  totalAmount: "₹" + appointment.total_amount,
  netAmount: "₹" + appointment.net_amount,
  paymentStatus: appointment.payment_status,
  paymentMethod: appointment.payment_method || "N/A",
  booking_status:appointment.booking_status || 'N/A',
  rescheduled_date:appointment.rescheduled_date ? new Date(appointment.rescheduled_date).toLocaleString() : "N/A",
  reportStatus: appointment.report_shared ? "Yes" : "No",
  createdAt: appointment.createdAt,
});
