 export const userOrderFlattenRow = (order) => ({
  OrderID: order.booking_id || "N/A",
  Name: order.displayName || "N/A",
  Email: order.email || "N/A",
  TotalPrice: order.totalPrice || "N/A",
  AmountPaid: order.amount_paid || "N/A",
  CouponUsed: order.coupon || "N/A",
  BookedDate: order.bookDate || "N/A",
  ScheduledDate: order.displayDate || "N/A",
  TimeSlot: order.timeslot || "N/A",
  TestNames: order.testNamesText || "N/A",
  PaymentMethod: order.paymentMethod || "N/A",
  PaymentStatus: order.paymentStatus || "N/A",
  ReportShared: order.report_shared ? "Yes" : "No",
  DML_Name: order.dmlName || "N/A",
  DML_Email: order.dmlEmail || "N/A",
  UserAddress: order.User?.address || "N/A",
  Pincode: order.User?.pincode || "N/A",
  State: order.User?.state || "N/A",
});
